name: flutter_schedule_view_example
description: Demonstrates how to use the flutter_schedule_view library.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.10
  intl: ^0.18.1
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_schedule_view:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - images/
