name: flutter_schedule_view
description: Displays a highly customizable schedule view which is able to display events
version: 0.1.0
homepage: https://github.com/kongpf8848/flutter_schedule_view

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  # This is needed for golden_toolkit's loading of fonts for testings to work.
  uses-material-design: true
